### ISSUE TITLE
SDK 데이터 서버로 보낼 때 에러 무한루프 도는 문제

### ISSUE THREAD

**Issue by junsushin-dev** [boostcamp-2020/Project11-B-Web-FE-Performance-Monitoring-Server#28]
서버에 API POST 요청이 fail 할 경우, 해당 에러가 또 잡혀서 재귀적으로 에러를 보내는 문제

서버가 꺼져있을 경우 항상 에러가 발생할 수 있음

**Comment by juyoungpark718** [comment]
fetch로 통신을 하는 부분에 대해서 catch로 에러를 잡으면, onunhandledrejection로 취급하지 않을 것 같다는 호진님의 의견을 참고해서 시도해보면 좋을 것 같습니다.
